# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyApp
  pod 'lottie-ios'
  pod 'AFNetworking'
  pod 'NMCLiveStreaming'
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
  pod 'SDWebImage'
  pod 'MyLayout'
  pod 'ASIHTTPRequest'
  pod 'UIColor-Utilities', '1.0.1'
  pod 'Masonry', '~> 1.1.0'
  inhibit_all_warnings!
end
